# Generated by Django 3.0.7 on 2020-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='author_name'),
        ),
    ]
