# Generated by Django 3.0.7 on 2020-06-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200613_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='upVotes',
        ),
        migrations.AddField(
            model_name='post',
            name='upVotes',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
