# Generated by Django 3.0.7 on 2020-06-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('board', '0005_auto_20200614_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
